### ISSUE TITLE
Official portrait for Brad Ashford - A000373

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#100]
![rep brad ashford official photo 2015-02-26_pnn_0001](https://cloud.githubusercontent.com/assets/3171982/7683439/32fa6294-fd4d-11e4-969a-f0bbe71b1f5e.jpg)

Bioguide: A000373
Name: Brad Ashford

Metadata
name: Office of Brad Ashford
link: https://ashford.house.gov/

**Comment by hugovk** [comment]
:100:
