### ISSUE TITLE
Official portrait for Mike Bishop - B001293

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#104]
![mike_bishop_headshot](https://cloud.githubusercontent.com/assets/3171982/7732457/675133ec-fef6-11e4-8776-d7a094e1fe29.jpg)

Bioguide: B001293
Name: Mike Bishop

Metadata
name: Official House Website for Mike Bishop
link: https://mikebishop.house.gov/

**Comment by hugovk** [comment]
It's the [same photo as the last one](https://github.com/hugovk/images/commit/ce226e6b2abd470d4e04bfcafd22d9142184445c) but colour, larger, less cropped.

**Comment by nickom** [comment]
Upgrade! :)
