### ISSUE TITLE
Daniel Donovan D000625 Photo

### ISSUE THREAD

**Issue by Yurokle** [unitedstates/images#109]
Name: Daniel Donovan
Bioguide ID: D000625
Image page: https://en.wikipedia.org/wiki/Dan_Donovan_(politician)#/media/File:Congressman_Daniel_Donovan.jpg
Image link: https://upload.wikimedia.org/wikipedia/commons/f/f1/Congressman_Daniel_Donovan.jpg

**Comment by hugovk** [comment]
Added in https://github.com/unitedstates/images/pull/110.
