### ISSUE TITLE
Travis CI and Coveralls

### ISSUE THREAD

**Issue by hugovk** [unitedstates/images#11]
I've added a Travis CI build. Everything's in the https://github.com/unitedstates/images/blob/gh-pages/.travis.yml file. 

It runs on all available Python versions (2.6, 2.7, 3.2, 3.3 and pypy, with 3.4 coming along any day now). It's allowed to fail for all versions but 2.7. It passes on 2.6 and 2.7 as Python 3 isn't supported yet. (Probably just the `print`s.)

It then runs the tests, with coverage, and checks for missing images. After a successful build it sends coverage to Coveralls and runs some basic static analysis (pep8, pyflakes).

Both Travis CI and Coveralls are free for open source, and you get reports like this (from my fork):
https://travis-ci.org/hugovk/images
https://coveralls.io/r/hugovk/images

Travis is really handy to check nothing gets broken on on other platforms, for each commit. Coverage isn't so useful as coverage is only 33%, but it doesn't hurt to enable. 

I don't see any particular need to show the badges in the README.

Please could you enable Travis CI and Coveralls for this repo?

**Comment by konklone** [comment]
Happy to turn these both on if you want, you're definitely an owner of this repo. FWIW, my opinion is that code coverage tools are generally not worth it. Especially for scrapers, and especially here when it's 33%, I do think it hurts to enable, where you're conditioning yourself to ignore a low number.

**Comment by konklone** [comment]
Also, thank you for submitting it as a PR even when self-merging, I like that pattern a lot. (Though maybe separate the commits a bit, as that PR did 3 unrelated things.)

I've enabled Travis CI. I think you actually have admin permissions for this repo, to enable the app on Coveralls if you really want.

**Comment by konklone** [comment]
Oh, one more comment -- my suggestion (and I'm going to do this on congress-legislators) is to cut down the supported Python versions a bit. It only needs to support the latest 2.X, the latest 3.X, and maybe PyPy, in my opinion. It's all your call on this repo, though.

**Comment by hugovk** [comment]
I have push/pull access to this repo but not admin, according to Travis:

> Sorry, but we can't find any repositories you have admin access to.
> Repositories without admin access
> You only have pull or push access to the repositories below.
>  unitedstates/image

---

> Also, thank you for submitting it as a PR even when self-merging, I like that pattern a lot.

I forked to my own repo so I could enable and test Travis, but working in a feature fork is the generally accepted way to do things. A PR was just an easy way to merge it back to this repo. It definitely makes it easier to group and gate things back, and to see the changes in one place.

> (Though maybe separate the commits a bit, as that PR did 3 unrelated things.)

(Agreed.)

---

> Oh, one more comment -- my suggestion (and I'm going to do this on congress-legislators) is to cut down the supported Python versions a bit. It only needs to support the latest 2.X, the latest 3.X, and maybe PyPy, in my opinion. It's all your call on this repo, though.

Yeah, I mainly put them all in to demonstrate what's available with Travis. It's kind of interesting to see the results of the others, and even allowed_failures for unsupported versions has some use: it advertises to others that a given version has been tested, so don't bother with that failing version. Although, less useful on small, scraper projects like this!

**Comment by konklone** [comment]
Oops, you're right - I just gave you admin access, you should have permissions now.
