### ISSUE TITLE
Make tests pass

### ISSUE THREAD

**Issue by konklone** [unitedstates/images#12]
The current commit is only passing under Python 2.6 and 2.7:

https://travis-ci.org/hugovk/images/builds/22171589

Now that we're under Travis' watchful eye, we should get the tests to all pass.

Is `scripts/missing.py` a good idea to run on Travis? It does network downloads, for example. It might be better to have a script which can run more quickly and doesn't tax Travis as much.

**Comment by hugovk** [comment]
> Is `scripts/missing.py` a good idea to run on Travis? It does network downloads, for example. It might be better to have a script which can run more quickly and doesn't tax Travis as much. 

I don't mind removing it. 

The only network stuff `missing.py` does is a git clone and a git fetch of the congress-legislators repo. `gpo_member_photos.py` is the one that does loads of fetches from www.memberguide.gpoaccess.gov.

Seeing as Travis is doing git clone anyway to get the images repo, another couple of gits aren't really a problem. 

As to whether it should be run -- it's not really essential, but it's fairly lightweight and gives us a historical report of missing images in the logs. And running it ensures it's working (to a lesser or greater extent).

**Comment by konklone** [comment]
It's totally your call. I actually didn't realize it only did a git clone, I thought it was hitting GPO. Sounds good to me.
