### ISSUE TITLE
Rep Warren Davidson (R-OH8) missing IMG

### ISSUE THREAD

**Issue by SteveKekacs** [unitedstates/images#122]
- Name: Rep Warren Davidson (R-OH8)
- BioguideID: D000626
- Navigating to Page With Img: 
  1. GOTO http://memberguide.gpo.gov/Home.html
  2. In the search bar in the top right corner type: "Davidson"
  3. Click on result.

**Comment by hugovk** [comment]
@Skekacs93 Thanks, added!
