### ISSUE TITLE
Eventually: convert URLs to HTTPS

### ISSUE THREAD

**Issue by konklone** [unitedstates/images#13]
Adding HTTPS support will make these images usable in secure environments, without mixed content warnings.

We have image URLs on a custom domain right now, which is great for portability (we can easily leave Github) but less good for HTTPS. Github supports HTTPS for Github Pages now, but only for `*.github.io` domains.

However, Cloudflare may change this game if they offer a free SSL-only plan, as [they say they will](https://twitter.com/CloudFlare/status/450390445365800961).

When that time comes, it's worth me putting Cloudflare in front of `theunitedstates.io` so that we can get an SSL terminator in front of everything, and have things encrypted end to end. I'm dropping this here as a reminder.

**Comment by hugovk** [comment]
@konklone can this be closed now?

**Comment by konklone** [comment]
Yep!
