### ISSUE TITLE
ADD: K000393, John Neely Kennedy

### ISSUE THREAD

**Issue by spencerthayer** [unitedstates/images#130]
Any of these reuse images would be fine.

https://www.google.com/search?q=K000393+John+Neely+Kennedy&tbm=isch&tbs=rimg:CZhKBvmxBDIvIjidxvnrYOWIHvzJ0oRRdm1zdfM3z96ECL4o9xilvrf54Ig0xDc76xLV2Rmolh2Iz4UtF8ZuukFqqyoSCZ3G-etg5YgeEVYoV1iqCAcfKhIJ_1MnShFF2bXMRFk-Io_1qKvusqEgl18zfP3oQIvhHRpdDW16T6oioSCSj3GKW-t_1ngEfNdYfeE7eFlKhIJiDTENzvrEtUR3Ht5V24p5ycqEgnZGaiWHYjPhRGfvy0MeyoG9SoSCS0Xxm66QWqrEfttyMkDUofc&tbo=u&sa=X&ved=0ahUKEwi8isnD5dTRAhUIOiYKHQrbBHAQ9C8ICQ&biw=1280&bih=703&dpr=2#q=K000393+John+Neely+Kennedy&newwindow=1&tbs=rimg:CZhKBvmxBDIvIjidxvnrYOWIHvzJ0oRRdm1zdfM3z96ECL4o9xilvrf54Ig0xDc76xLV2Rmolh2Iz4UtF8ZuukFqqyoSCZ3G-etg5YgeEVYoV1iqCAcfKhIJ_1MnShFF2bXMRFk-Io_1qKvusqEgl18zfP3oQIvhHRpdDW16T6oioSCSj3GKW-t_1ngEfNdYfeE7eFlKhIJiDTENzvrEtUR3Ht5V24p5ycqEgnZGaiWHYjPhRGfvy0MeyoG9SoSCS0Xxm66QWqrEfttyMkDUofc,sur:fc&tbm=isch

**Comment by spencerthayer** [comment]
This one is probably the best. http://www.gannett-cdn.com/-mm-/b5dc1907aa6aae1e93ace3a501cd1b2a39dcf9a9/c=0-0-1557-2076&r=537&c=0-0-534-712/local/-/media/2015/05/13/Shreveport/B9317341212Z.1_20150513182337_000_GQ3APEJRB.1-0.jpg

**Comment by hugovk** [comment]
Closing in favour of https://github.com/unitedstates/images/pull/127.
