### ISSUE TITLE
Tom Udall has Mark Udall's photo

### ISSUE THREAD

**Issue by eads** [unitedstates/images#131]
Here's Tom Udall, Senator from NM: https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Tom_Udall_official_Senate_portrait.jpg/220px-Tom_Udall_official_Senate_portrait.jpg

The photo for his bioguideid shows his cousin Mark Udall instead: https://github.com/unitedstates/images/blob/gh-pages/congress/450x550/U000038.jpg

**Comment by hugovk** [comment]
They look correct to me, I think you've got the bioguide IDs mixed up.

---

Let's first check whose bioguide ID **U000038** belongs to.

https://github.com/unitedstates/congress-legislators/blob/master/legislators-historical.yaml has:
* U000038 Mark Udall

https://github.com/unitedstates/congress-legislators/blob/master/legislators-current.yaml#L2581 has:
* U000039 Tom Udall

---

On the left: [U000038 Mark Udall from this repo](https://github.com/unitedstates/images/blob/gh-pages/congress/225x275/U000038.jpg).
On the right: [U000039 Tom Udall from this repo](https://github.com/unitedstates/images/blob/gh-pages/congress/225x275/U000039.jpg).
![U000038](https://github.com/unitedstates/images/blob/gh-pages/congress/225x275/U000038.jpg?raw=true) ![U000039](https://github.com/unitedstates/images/blob/gh-pages/congress/225x275/U000039.jpg?raw=true)

---

On the left: U000038 [Mark Udall from Wikipedia](https://en.wikipedia.org/wiki/Mark_Udall).
On the right: U000039 [Tom Udall from Wikipedia](https://en.wikipedia.org/wiki/Tom_Udall).
 ![Mark](https://cloud.githubusercontent.com/assets/1324225/22608901/87f0a322-ea67-11e6-81de-e60949468a9c.png) ![Tom](https://cloud.githubusercontent.com/assets/1324225/22608860/564b5056-ea67-11e6-989f-45c615005d61.png)

**Comment by eads** [comment]
Interesting. Let me go back to the original data and see what's up. This was pulled from the House clerk's 115th congress roll call spreadsheet, but it's possible the data got messed up somehow. thanks for the quick reply
