### ISSUE TITLE
Headshot and portrait for Sen. Cindy Hyde-Smith (Bioguide ID H001079)

### ISSUE THREAD

**Issue by jalefkowit** [unitedstates/images#161]
- Official headshot: https://www.hydesmith.senate.gov/sites/default/files/Hyde%20Smith_Cindy-041718-Headshot.jpg
- Official portrait: https://www.hydesmith.senate.gov/sites/default/files/Hyde%20Smith_Cindy-2018-Offical-Portrait.jpg

Both files taken from her Senate website, [https://www.hydesmith.senate.gov/](https://www.hydesmith.senate.gov/).

[Wikipedia confirms](https://en.wikipedia.org/wiki/Cindy_Hyde-Smith#/media/File:Cindy_Hyde-Smith_official_photo.jpg) that the headshot is her official Senate headshot, and therefore in the public domain.

**Comment by hugovk** [comment]
Thanks, added in https://github.com/unitedstates/images/pull/163.
