### ISSUE TITLE
Add missing senators from the 116th congress

### ISSUE THREAD

**Issue by pandringa** [unitedstates/images#167]
Here's a list of the newly-seated senators who are still missing photos, and a possible photo for each. I'm happy to submit a PR with these photos, if that would be helpful to get them merged in.

Thanks!

- [Rick Scott - S001217](https://www.budget.senate.gov/imo/media/image/Official-Portrait_RLS.jpg) (This photo is available on the [Bioguide](http://bioguide.congress.gov/scripts/biodisplay.pl?index=S001217) and [Budget committee site](https://www.budget.senate.gov/about/committee-members), and [Wikipedia lists it](https://en.wikipedia.org/wiki/Rick_Scott#/media/File:Sen._Rick_Scott_(R-FL)_official_Senate_portrait.jpg) as public domain)
![Rick Scott](https://www.budget.senate.gov/imo/media/image/Official-Portrait_RLS.jpg)

- [Mitt Romney - R000615](https://upload.wikimedia.org/wikipedia/commons/7/7f/Mitt_Romney_official_US_Senate_portrait.jpg) (See #166)
![Mitt Romney](https://upload.wikimedia.org/wikipedia/commons/7/7f/Mitt_Romney_official_US_Senate_portrait.jpg)

- [Joshua Hawley - H001089](https://www.judiciary.senate.gov/imo/media/image/Hawley_Josh-010919-RMB-042a04_300.png) (This photo is available on [Sen. Hawley's website](https://hawley.senate.gov) and the [Judiciary Committee site](https://www.judiciary.senate.gov), and [Wikipedia lists it](https://en.wikipedia.org/wiki/Josh_Hawley#/media/File:Josh_Hawley_official_photo.jpg) as public domain)
![Josh Hawley](https://www.judiciary.senate.gov/imo/media/image/Hawley_Josh-010919-RMB-042a04_300.png)

- [Mike Braun - B001310](https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Mike_Braun%2C_Official_Portrait%2C_116th_Congress.jpg/1280px-Mike_Braun%2C_Official_Portrait%2C_116th_Congress.jpg) (A [Wikipedia user](https://commons.wikimedia.org/wiki/File:Mike_Braun,_Official_Portrait,_116th_Congress.jpg) found this full-sized version of the photo on the [Health, Education, Labor, and Pensions committee site](https://www.help.senate.gov/about/members))
![Mike Braun](https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Mike_Braun%2C_Official_Portrait%2C_116th_Congress.jpg/1280px-Mike_Braun%2C_Official_Portrait%2C_116th_Congress.jpg)

**Comment by hugovk** [comment]
Thanks, a PR would be great!
