### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by swt83** [unitedstates/images#17]
I'm running this:

``` bash
python scripts/gpo_member_photos.py
```

Getting this:

``` bash
Traceback (most recent call last):
  File "scripts/gpo_member_photos.py", line 393, in <module>
    member_links = get_front_page(br, args.congress, args.delay)
  File "scripts/gpo_member_photos.py", line 63, in get_front_page
    br.select_form(nr=0)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 524, in select_form
    raise FormNotFoundError("no form matching "+description)
mechanize._mechanize.FormNotFoundError: no form matching nr 0
```

I'm on a Mac.  I don't speak Python.

**Comment by konklone** [comment]
Looks like GPO might have changed their website around! I'll defer to @hugovk and @handlers on how to handle it.

**Comment by plantfansam** [comment]
Yeah -- seems to me that there must have been an update to the landing page; looks like it's AJAXing in content now. There's not even a form tag in the source anymore. 

Happy to take this on unless someone else wants it.

**Comment by hugovk** [comment]
@handlers Go for it! Let me know if you've any questions about the current implementation.

**Comment by plantfansam** [comment]
Passing the buck to @rshorey

**Comment by hugovk** [comment]
Fixed in https://github.com/unitedstates/images/pull/18.

Thanks!

**Comment by swt83** [comment]
``` bash
→ git pull origin master
fatal: Couldn't find remote ref master
```

Why you delete `master` branch? :(

**Comment by hugovk** [comment]
We use `gh-pages` as the main branch so the images are hosted online like http://theunitedstates.io/images/congress/[size]/[bioguide].jpg, and it makes it easier to work just with that one branch.
