### ISSUE TITLE
Tom Malinowski NJ,7  photo

### ISSUE THREAD

**Issue by syntheticgoo** [unitedstates/images#177]
- Tom Malinowski
- https://www.congress.gov/img/member/m001203.jpg, https://www.congress.gov/member/tom-malinowski/M001203?q={%22search%22:[%22malinowski%22]}&s=1&r=1&searchResultViewType=expanded
- official congress.gov site, provided by member office

**Comment by syntheticgoo** [comment]
![Rep  Malinowski Official Photo](https://user-images.githubusercontent.com/4314868/71018949-4c9d5880-20ae-11ea-95c0-673b73d95de6.jpg)
Here's a fullsize image, shared by the Member's office.

**Comment by hugovk** [comment]
Thanks, added in #178!
