### ISSUE TITLE
Incorrect Image

### ISSUE THREAD

**Issue by eatmorebacon** [unitedstates/images#189]
It looks like the image for Rep. John Joyce of PA (https://theunitedstates.io/images/congress/original/J000302.jpg) is actually one of Rep. David Joyce of OH.  David Joyce is bioguide J000295. The image at J000295 is David Joyce, although not the current GPO image which is at J000302.

Attached is GPO search with both Joyces.  

<img width="275" alt="gpo_joyce" src="https://user-images.githubusercontent.com/10585303/107770562-9b24a200-6d07-11eb-8e70-82ad4c66805d.png">

**Comment by hugovk** [comment]
Well spotted, thanks for the report!

I've created #190 to fix it.
