### ISSUE TITLE
Update photo

### ISSUE THREAD

**Issue by jatt64** [unitedstates/images#193]
Ted Deutch D000610

OLD: https://github.com/unitedstates/images/blob/gh-pages/congress/450x550/D000610.jpg

Replace with: https://memberguide.gpo.gov/PictorialImages/116_RP_FL_22_Deutch_Theodore.jpg
Or
https://www.congress.gov/img/member/d000610.jpg

**Comment by hugovk** [comment]
Thanks, updated!
