### ISSUE TITLE
New member low-res b&w photos

### ISSUE THREAD

**Issue by JoshData** [unitedstates/images#20]
There's no telling when new Members of Congress will get photos on the memberguide site. It could be soon or it could be far off. In the meanwhile, someone could scrape:

http://www.gpo.gov/fdsys/browse/collection.action?collectionCode=GPO&browsePath=Congressional+Pictorial+Directory%2F114th+Congress&isCollapsed=false&leafLevelBrowse=false&isDocumentResults=true&ycord=0

Which has not-very-high-res black and white photos of new members. I used to scrape these PDFs by hand. It was the WORST thing ever. But it's there.

**Comment by plantfansam** [comment]
So I have manually parsed through the new member guide images (thanks to @JoshData ripping the images from the PDF), and many of them are up on a [fork](https://github.com/handlers/images/commits/gh-pages). 

I don't know this repo that well, so I haven't made a pull request just yet. If anyone more familiar with the project wants to provide guidance on getting that merge-ready, that would be awesome.

**Comment by hugovk** [comment]
@handlers I've had a quick check and it looks good! 

It also looks merge ready. Just go ahead and create a PR.

Thanks!
