### ISSUE TITLE
Sheila Cherfilus-McCormick

### ISSUE THREAD

**Issue by fre5** [unitedstates/images#211]
| Id | Name | Link to source | Source | Public domain |
|:---|:-----|:---------------|:-------|:--------------|
| C001127 | Sheila Cherfilus-McCormick | [LINK](https://upload.wikimedia.org/wikipedia/commons/0/07/Rep._Sheila_Cherfilus-McCormick_-_117th_Congress.jpg) | Wikipedia | Yes |

**Comment by mdrayer** [comment]
This is available now, so we can close this ticket.
- https://theunitedstates.io/images/congress/original/C001127.jpg
- https://theunitedstates.io/images/congress/450x550/C001127.jpg
- https://theunitedstates.io/images/congress/225x275/C001127.jpg
- https://github.com/unitedstates/images/blob/gh-pages/congress/metadata/C001127.yaml
