### ISSUE TITLE
Update script for 114th congress

### ISSUE THREAD

**Issue by hugovk** [unitedstates/images#22]
By default the script is searching for the 113rd congress. It should be changed to 114 by default in:

``` python
    parser.add_argument(
        '-n', '--congress', default='113',
        help="Congress session number, for example: 110, 111, 112, 113")
```

But when running on the 114, it doesn't find any links:

```
$ python scripts/gpo_member_photos.py -n 114
Updating the congress-legislators repo...
The system cannot find the path specified.
Submit congress session number: 114
Links: 0
Found a total of 0 member links

---
Didn't resolve Bioguide IDs: 0
Welcome to Git (version 1.9.5-preview20141217)


Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
Silently Installing...
mkdir: cannot create directory `congress/225x275': File exists
mkdir: cannot create directory `congress/450x550': File exists
```

**Comment by rshorey** [comment]
It's possible the whole site is down this morning. I've been trying to check it manually and not getting anything.

**Comment by plantfansam** [comment]
@hugovk, I called GPO to ask about the [member guide website](http://memberguide.gpo.gov/), and someone there estimated that it would be updated for the 114th in June. So assuming that that's true, `gpo_members.py` probably isn't going to work for the 114th for a while. I assume that Booker (ref #8) — like Rep. Brat, etc. — isn't on the GPO member guide for the 113th because he took office through a special election. Which I believe means that missing legislators will remain a mostly manual job unless we find a new data source. 

@rshorey bioguide is also down for me, but the GPO member guide is up.

**Comment by jonrobinson2** [comment]
Hm. You guys don't pull from this site? http://bioguide.congress.gov/scripts/biodisplay.pl?index=P000612. The logic for scraping the images and all that seems relatively simple/predictible as Perdue's link is:

http://bioguide.congress.gov/bioguide/photo/P/P000612.jpg

Just curious.

**Comment by wilsaj** [comment]
@jonrobinson2 Have to be careful with that because bioguide photos may be subject to copyright. From http://bioguide.congress.gov/copyright.htm:

> Images on this site are provided as a contribution to education and scholarship. Not all images are in the public domain; some images may be protected by the U.S. Copyright Law (Title 17, U.S.C.). Do not duplicate without permission from copyright holder. Copyright information is provided whenever possile, but it is ultimately the responsibility of the user to determine and satisfy the copyright and other restrictions.

**Comment by JoshData** [comment]
All of the photos for historical MoCs on GovTrack come from bioguide.... under a hopeful premise that the really old photos are out of copyright. :) https://www.govtrack.us/data/photos/

**Comment by jonrobinson2** [comment]
Interesting. That is sufficiently vague language. My thought is that it might be the other way around...that the older images would be where the bioguides site would have a copyright claim over an image that only they own? I'm probably wrong on this though.
