### ISSUE TITLE
Add instructions on how to grab a single path

### ISSUE THREAD

**Issue by Hainish** [unitedstates/images#23]
Occasionally for https://github.com/efforg/congress-forms-test we have to pull the latest 225x275 images.  Instead of pulling the entire repo with the much larger images, I'm able to use github's support of `svn` to grab _just_ that path:

```
svn checkout https://github.com/unitedstates/images/trunk/congress/225x275
```

You may want to add instructions on how to do this in the `README.md`

**Comment by konklone** [comment]
Fixed by #24.
