### ISSUE TITLE
Official portrait for Amata Coleman Radewagen - R000600

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#26]
![amata official portrait](https://cloud.githubusercontent.com/assets/3171982/6948920/f0bedc04-d87e-11e4-8f7f-d4bb281fbddf.jpg)

Bioguide: R000600
Name: Amata Coleman Radewagen
This image was received after contacting the office. Below is the correspondence with the office:

---

Please see attachment.

Jared Michael P. Christel
Legislative Correspondent
Congresswoman Aumua Amata C. Radewagen
American Samoa At Large District (AQ00)
1339 Longworth HOB
T: (202) 225-8577
F: (202)225-8757

-----Original Message-----
From: webforms@hhws-www2.house.gov [mailto:webforms@hhws-www2.house.gov]
Sent: Monday, March 30, 2015 5:05 PM
To: WebForms, RadewagenAQ
Subject: Website Problem

 WEB PAGE WITH PROBLEM: https://radewagen.house.gov

 NATURE OF PROBLEM:
 I can't find Rep. Radewagen's official House portrait. I'm looking to add the government made, copyright free image to a repository of images of members of Congress that others can freely use. Please let me know where I can find this.

 Thank you!

**Comment by hugovk** [comment]
Re-open to add metadata: https://github.com/unitedstates/images/tree/gh-pages/congress/metadata
