### ISSUE TITLE
Official portrait for David Perdue - P000612

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#27]
![davidperdueofficialheadshot2015](https://cloud.githubusercontent.com/assets/3171982/6949367/0375f8de-d882-11e4-8c5b-9e8a6a76a663.jpg)

Bioguide: P000612
Name: David Perdue
Image from his Senate website here:
http://www.perdue.senate.gov/sites/default/files/DavidPerdueOfficialHeadshot2015.jpg

**Comment by hugovk** [comment]
Re-open to add metadata: https://github.com/unitedstates/images/tree/gh-pages/congress/metadata

**Comment by nickom** [comment]
Metadata:

name: Official Senate Website for David Perdue
link: http://www.perdue.senate.gov/sites/default/files/DavidPerdueOfficialHeadshot2015.jpg
