### ISSUE TITLE
Official portrait for Joni Ernst - E000295

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#28]
![sen joni ernst - official portrait](https://cloud.githubusercontent.com/assets/3171982/6949435/6fd19312-d882-11e4-86f1-64eecdc4eb05.jpg)

Bioguide: E000295
Name: Joni Ernst
Image from her Senate website here:
http://www.ernst.senate.gov/sites/default/files/Sen.%20Joni%20Ernst%20-%20Official%20Portrait.jpg

**Comment by hugovk** [comment]
Re-open to add metadata: https://github.com/unitedstates/images/tree/gh-pages/congress/metadata

**Comment by nickom** [comment]
Metadata:

name: Official Senate Website for Joni Ernst
link: http://www.ernst.senate.gov/sites/default/files/Sen.%20Joni%20Ernst%20-%20Official%20Portrait.jpg
