### ISSUE TITLE
Official portrait for Mike Rounds - R000605

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#29]
![official portrait](https://cloud.githubusercontent.com/assets/3171982/6949870/eeb92efe-d884-11e4-8cd5-0fb6e09ad19a.jpg)

Bioguide: R000605
Name: Mike Rounds
Image provided by his press secretary, Katie Douglas, after emailing a request for the government-made, copyright-free image.

**Comment by hugovk** [comment]
Re-open to add metadata: https://github.com/unitedstates/images/tree/gh-pages/congress/metadata

**Comment by nickom** [comment]
Metadata:

name: Provided by email from Katie Douglas, the press secretary for Mike Rounds 
link: Not available
