### ISSUE TITLE
Make script work in new repo

### ISSUE THREAD

**Issue by konklone** [unitedstates/images#3]
- Cloning the YAML from git on demand instead of looking for it nearby
- Have it output to the `congress/originals` directory
- Bring over any `utils` functions it was using

**Comment by hugovk** [comment]
- Output image directory set to `congress/originals`.
- Run from root of `images` like:
  `python scripts/gpo_member_photos.py`
- If the YAML isn't present, it downloads it from https://raw2.github.com/unitedstates/congress-legislators/master/legislators-current.yaml
- No `utils` are used.
- Added a `.gitignore` from https://github.com/github/gitignore and added legislators-current.yaml and cache/

Done in:
https://github.com/unitedstates/images/commit/ef4fd3ac88c45736c92b6350dd614a37d8e4cf0f

**Comment by konklone** [comment]
We've really got to get a gh-pages output workflow going for our legislator
data, so you don't have to git clone or use raw.github.com. This is just
fine, just making a note for myself.
