### ISSUE TITLE
Official portrait for Daniel Sullivan - S001198

### ISSUE THREAD

**Issue by nickom** [unitedstates/images#30]
![dssullivan official portrait](https://cloud.githubusercontent.com/assets/3171982/6950050/313ecb48-d886-11e4-9064-92d4b7a4c1d6.jpg)

Bioguide: S001198
Name: Daniel Sullivan
Image provided by his press secretary, Mike Anderson, after emailing a request for the government-made, copyright-free image.

**Comment by hugovk** [comment]
Re-open to add metadata: https://github.com/unitedstates/images/tree/gh-pages/congress/metadata

**Comment by nickom** [comment]
Metadata:

name: Provided by email from Mike Anderson, the press secretary for Daniel Sullivan 
link: Not available
