### ISSUE TITLE
Document setup, add requirements.txt

### ISSUE THREAD

**Issue by konklone** [unitedstates/images#5]
Make a `requirements.txt` file with any `pip` requirements, and document the get-up-and-go process.

**Comment by hugovk** [comment]
I've never made a `requirements.txt` before. The three things this needs are BeautifulSoup, PyYAML and mechanize, and all were pip installed this week.

`pip freeze` tells me they're:

```
BeautifulSoup==3.2.1
PyYAML==3.10
mechanize==0.2.5
```

Added in:
https://github.com/unitedstates/images/commit/2f0dcdd27bad16358072e7819b8f4f5890465e62
