### ISSUE TITLE
Adding credit files to each image

### ISSUE THREAD

**Issue by JoshData** [unitedstates/images#6]
If we want to include images from other sources, we should add metadata to each image with source information. Might be YAML like:

```
name: GPO Member Guide
link: http://memberguide.gpo.gov
```

**Comment by konklone** [comment]
How about adding EXIF data?

**Comment by JoshData** [comment]
That is not terribly easy to process, not clear in git ...

**Comment by konklone** [comment]
All right, I can be down with metadata, YAML would even be readable from the gh-pages branch.

**Comment by hugovk** [comment]
So,YAML (`credits.yaml`? `metadata.yaml`? And where?) looking something like this?

```
 - file: Y000064.jpg
   name: GPO Member Guide
   link: http://memberguide.gpo.gov
 - file: Y000065.jpg
   name: GPO Member Guide
   link: http://memberguide.gpo.gov
```

Or?

```
 - bioguide: Y000064
   name: GPO Member Guide
   link: http://memberguide.gpo.gov
 - bioguide: Y000065
   name: GPO Member Guide
   link: http://memberguide.gpo.gov
```

Or something else?

**Comment by JoshData** [comment]
Actually I had in mind a separate file per image in a new metadata directory. (This just parallels how I maintain that info on GovTrack now.)

**Comment by hugovk** [comment]
Ah, ok, so something like:
- `/metadata/Y000064.yaml`:

```
name: GPO Member Guide
link: http://memberguide.gpo.gov
```
- `/metadata/Y000065.yaml`:

```
name: GPO Member Guide
link: http://memberguide.gpo.gov
```

**Comment by JoshData** [comment]
Thanks!
