### ISSUE TITLE
Create a bower.json file

### ISSUE THREAD

**Issue by Hainish** [unitedstates/images#73]
Bower isn't just useful for javascript - compiling static assets like congressional images into a bower repo will make it so that it's easy to include and update congressional images by 3rd party apps.

For example, if you're using "rails-assets.org" in your rails app, which takes bower as its data source, in rails all you would have to do is include something like:

```
gem "rails-assets-congress-images"
```

Then next time a new congress comes in, just do a `bundle update rails-assets-congress-images` and it pulls all those new images in without the developer having to go out and fetch them

**Comment by hugovk** [comment]
@Hainish No objections from me, and seems no objections from anyone else. 

Would you like to submit a pull request?

**Comment by spencerthayer** [comment]
+1 this.

**Comment by hugovk** [comment]
A PR is welcome to add this! 

Closing in the meantime.
