### ISSUE TITLE
Missing metadata files in 9dc36c363484b793eb68c73ded558e8a65e02dc9

### ISSUE THREAD

**Issue by JoshData** [unitedstates/images#99]
The photos added in 9dc36c363484b793eb68c73ded558e8a65e02dc9 are missing metadata files.

**Comment by hugovk** [comment]
@JoshData Yep, I forgot those in the merged PR #31, so added them in commits https://github.com/hugovk/images/commit/be9a1f9f0fe98f20282acee086c3810070372179 and https://github.com/hugovk/images/commit/71e9a56fbb721cc26439584aaed2b6121df89786, which are in the next PR, #39.

**Comment by JoshData** [comment]
Ahhha, thanks.
